<?php
/*
* generate-readme.php - Regenerates Tests/README.md from the test suite itself.
*
* Source of truth is a one-line PHPDoc-style comment directly above each `public function
* testXxx()` method - this script does nothing but collect those (plus a per-file count) into
* Tests/README.md, so the doc can never drift from what the tests actually say about
* themselves. Run after adding/renaming/removing a test:
*
*   php Tests/generate-readme.php
*
* CI (ci.yml's docs-check job) fails if the committed file doesn't match this script's output.
*/

$root = dirname(__DIR__);
$testsDir = __DIR__;

function find_php_files($dir)
{
    $files = array();
    $iterator = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($dir, FilesystemIterator::SKIP_DOTS)
    );
    foreach ($iterator as $file) {
        if ($file->getExtension() === 'php') {
            $files[] = $file->getPathname();
        }
    }
    sort($files);
    return $files;
}

// Finds the source file a "FooTest.php" file is testing, by searching the whole repo
// (excluding Tests/ itself) for a file literally named "Foo.php".
function find_source_file($root, $className)
{
    $target = preg_replace('/Test$/', '', $className) . '.php';
    $iterator = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($root, FilesystemIterator::SKIP_DOTS)
    );
    foreach ($iterator as $file) {
        if ($file->getFilename() !== $target) {
            continue;
        }
        $path = str_replace('\\', '/', $file->getPathname());
        if (strpos($path, '/Tests/') !== false || strpos($path, '/.git/') !== false) {
            continue;
        }
        return $path;
    }
    return null;
}

function relative_path($root, $absolutePath)
{
    $root = str_replace('\\', '/', $root);
    $absolutePath = str_replace('\\', '/', $absolutePath);
    if (strpos($absolutePath, $root . '/') === 0) {
        return substr($absolutePath, strlen($root) + 1);
    }
    return $absolutePath;
}

// Extracts each `public function testXxx()` plus the /** ... */ docblock immediately above
// it (only whitespace allowed in between), if any.
function parse_test_file($path)
{
    $source = file_get_contents($path);

    $className = null;
    if (preg_match('/class\s+(\w+)\s+extends/', $source, $m)) {
        $className = $m[1];
    }

    $tests = array();
    if (preg_match_all('/public function (test\w+)\s*\(/', $source, $matches, PREG_OFFSET_CAPTURE)) {
        foreach ($matches[1] as $i => $match) {
            list($name, $offset) = $match;
            $before = substr($source, 0, $offset);

            $purpose = null;
            if (preg_match_all('#/\*\*(.*?)\*/#s', $before, $docMatches, PREG_OFFSET_CAPTURE)) {
                $lastIndex = count($docMatches[0]) - 1;
                list($body, $bodyOffset) = $docMatches[1][$lastIndex];
                $fullMatch = $docMatches[0][$lastIndex][0];
                $matchEnd = $docMatches[0][$lastIndex][1] + strlen($fullMatch);
                $gap = substr($before, $matchEnd);
                if (trim($gap) === '') {
                    $lines = explode("\n", $body);
                    $lines = array_map(function ($line) {
                        return preg_replace('/^\s*\*\s?/', '', $line);
                    }, $lines);
                    $purpose = trim(preg_replace('/\s+/', ' ', implode(' ', $lines)));
                }
            }

            $tests[] = array('name' => $name, 'purpose' => $purpose);
        }
    }

    return array('class' => $className, 'tests' => $tests);
}

function markdown_escape_cell($text)
{
    return str_replace('|', '\\|', $text);
}

$testFiles = array_filter(find_php_files($testsDir), function ($path) {
    return substr($path, -8) === 'Test.php';
});

$parsed = array();
$totalTests = 0;
foreach ($testFiles as $path) {
    $info = parse_test_file($path);
    $sourceFile = find_source_file($root, $info['class']);
    $parsed[] = array(
        'testFile' => relative_path($testsDir, $path),
        'class' => $info['class'],
        'sourceFile' => $sourceFile ? relative_path($root, $sourceFile) : null,
        'tests' => $info['tests'],
    );
    $totalTests += count($info['tests']);
}

$out = "# Test coverage\n\n";
$out .= "PHPUnit tests, run via `.github/workflows/ci.yml`'s `unit-tests-php8*` jobs\n";
$out .= "(`php phpunit.phar --configuration phpunit.xml`, PHP 8.1+ - see the main\n";
$out .= "[README](../README.md#supported-php-versions)). `Tests/Stubs/` holds the\n";
$out .= "fakes these tests are built on (`FakeDb`, `StubBot`, `FakeSettings`,\n";
$out .= "`FakeTimerCore`, etc.) rather than a real database/AO connection.\n\n";
$out .= "**This file is generated by `php Tests/generate-readme.php` - do not edit it\n";
$out .= "directly.** Source of truth is the one-line docblock above each test method.\n\n";

$out .= "## Coverage summary\n\n";
$out .= "| Class under test | Test file | # Tests |\n";
$out .= "| --- | --- | --- |\n";
foreach ($parsed as $entry) {
    $sourceClass = preg_replace('/Test$/', '', $entry['class']);
    if ($entry['sourceFile']) {
        $classCell = "[`{$sourceClass}`](../{$entry['sourceFile']})";
    } else {
        $classCell = "`{$sourceClass}`";
    }
    $out .= "| $classCell | [`{$entry['testFile']}`]({$entry['testFile']}) | " . count($entry['tests']) . " |\n";
}
$out .= "| **Total** | | **$totalTests** |\n\n";

$out .= "Everything else in `Modules/`/`Sources/`/`Main/` (the bulk of the codebase)\n";
$out .= "has no automated coverage yet - it's exercised manually against a live bot\n";
$out .= "instead.\n";

foreach ($parsed as $entry) {
    $out .= "\n## `{$entry['testFile']}`\n\n";
    $out .= "| Test | Purpose |\n";
    $out .= "| --- | --- |\n";
    foreach ($entry['tests'] as $test) {
        $purpose = $test['purpose'] !== null ? $test['purpose'] : '_(no docblock)_';
        $out .= "| `{$test['name']}` | " . markdown_escape_cell($purpose) . " |\n";
    }
}

file_put_contents($testsDir . '/README.md', $out);
echo "Wrote Tests/README.md ($totalTests tests across " . count($parsed) . " file(s)).\n";
